package discover

// defaultWordlist is a compact list of the most common subdomain labels.
// For deeper coverage pass --wordlist with a larger file (e.g. SecLists).
var defaultWordlist = []string{
	"www", "mail", "ftp", "webmail", "smtp", "pop", "pop3", "imap", "ns1", "ns2",
	"ns3", "ns4", "dns", "dns1", "dns2", "mx", "mx1", "mx2", "email", "cpanel",
	"whm", "autodiscover", "autoconfig", "test", "dev", "staging", "stage",
	"prod", "production", "qa", "uat", "demo", "sandbox", "api", "api-dev",
	"api-staging", "apidocs", "developer", "developers", "docs", "doc",
	"documentation", "support", "help", "helpdesk", "kb", "wiki", "blog",
	"news", "shop", "store", "cart", "checkout", "pay", "payment", "payments",
	"billing", "invoice", "admin", "administrator", "adm", "portal", "dashboard",
	"panel", "console", "manage", "management", "login", "signin", "sso", "auth",
	"oauth", "account", "accounts", "my", "secure", "vpn", "remote", "gateway",
	"gw", "proxy", "cache", "cdn", "static", "assets", "img", "images", "media",
	"video", "videos", "download", "downloads", "files", "file", "upload",
	"uploads", "share", "drive", "cloud", "storage", "s3", "backup", "backups",
	"db", "database", "mysql", "postgres", "mssql", "mongo", "redis", "sql",
	"git", "gitlab", "github", "svn", "ci", "jenkins", "build", "deploy",
	"registry", "docker", "k8s", "kube", "kubernetes", "grafana", "kibana",
	"prometheus", "metrics", "monitor", "monitoring", "status", "health",
	"stats", "analytics", "log", "logs", "logging", "elk", "elastic", "search",
	"app", "apps", "mobile", "m", "web", "web1", "web2", "host", "server",
	"server1", "server2", "vps", "client", "clients", "customer", "customers",
	"partner", "partners", "vendor", "internal", "intranet", "extranet",
	"corp", "office", "hr", "crm", "erp", "jira", "confluence", "chat", "im",
	"talk", "meet", "conference", "video-conf", "voip", "sip", "pbx", "fax",
	"old", "new", "beta", "alpha", "preview", "next", "v1", "v2", "v3", "edge",
	"origin", "lb", "loadbalancer", "router", "firewall", "fw", "ns", "smtp1",
	"smtp2", "relay", "mta", "lists", "list", "newsletter", "marketing",
	"promo", "ads", "ad", "track", "tracking", "pixel", "go", "link", "links",
	"url", "redirect", "r", "t", "click", "events", "event", "calendar", "cal",
	"booking", "reserve", "ticket", "tickets", "feedback", "survey", "forms",
	"form", "contact", "about", "careers", "jobs", "press", "investors",
	"legal", "privacy", "terms", "gallery", "photos", "music", "podcast",
	"radio", "tv", "live", "stream", "streaming", "play", "game", "games",
	"forum", "forums", "community", "social", "connect", "members", "member",
	"user", "users", "profile", "profiles", "id", "identity", "key", "keys",
	"vault", "secrets", "config", "configs", "settings", "tools", "tool",
	"utils", "utility", "service", "services", "svc", "micro", "ms", "gateway2",
}
